services:
  - type: web
    name: autotube-ai-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PEXELS_API_KEY
        value: f9pRnqk0T38aFRraTo5NugtO8ow9AJ1u6TBBoBAtqv4yrlv3Sz5g4CyU
